import streamlit as st


def render_deck_preview(platform: str, audits_df, snapshot_mode: bool = False):
    st.markdown("### Deck Preview")
    st.markdown(
        "<div style='font-size:0.82rem;color:#6b7280;margin-bottom:16px;'>"
        "Preview the quarter-end audit summary deck for this platform."
        "</div>",
        unsafe_allow_html=True,
    )

    commentary = st.session_state.get("commentary", {}).get(platform, "")

    owned = audits_df[audits_df["audit_type"] == "Owned Audit"]
    inscope_ae = audits_df[audits_df["audit_type"] == "In-Scope AE"]
    indirect = audits_df[audits_df["audit_type"] == "Indirect"]
    direct_count = len(owned) + len(inscope_ae)
    total_count = len(audits_df)
    total_issues = int(audits_df["issue_count"].sum())
    complete_count = len(audits_df[audits_df["status"] == "Complete"])

    with st.container(border=True):
        # Deck header
        st.markdown(
            f"<div style='background:#1a1f2e;color:#fff;padding:20px 24px;border-radius:6px;margin-bottom:16px;'>"
            f"<div style='font-size:0.75rem;color:#93c5fd;text-transform:uppercase;letter-spacing:0.1em;'>Q2 FY2025 · Quarter End Audit Summary</div>"
            f"<div style='font-size:1.6rem;font-weight:700;margin-top:4px;'>{platform}</div>"
            f"<div style='font-size:0.85rem;color:#9ca3af;margin-top:4px;'>Feb 1 – Apr 30, 2025 · Primary Cutoff Apr 15 · Hard Close Apr 30</div>"
            f"</div>",
            unsafe_allow_html=True,
        )

        # Coverage summary row
        c1, c2, c3, c4 = st.columns(4)
        cards = [
            ("Total Footprint", str(total_count), "#1a1f2e"),
            ("Direct Coverage", str(direct_count), "#5b21b6"),
            ("Indirect Coverage", str(len(indirect)), "#1d4ed8"),
            ("Open Issues", str(total_issues), "#dc2626"),
        ]
        for col, (label, val, color) in zip([c1, c2, c3, c4], cards):
            with col:
                st.markdown(
                    f"<div style='border:1px solid #e5e7eb;border-radius:6px;padding:12px;text-align:center;'>"
                    f"<div style='font-size:0.72rem;color:#6b7280;text-transform:uppercase;font-weight:600;'>{label}</div>"
                    f"<div style='font-size:2rem;font-weight:700;color:{color};'>{val}</div>"
                    f"</div>",
                    unsafe_allow_html=True,
                )

        st.markdown("<div style='height:16px;'></div>", unsafe_allow_html=True)

        # Status breakdown
        st.markdown("**Audit Status Breakdown**")
        status_counts = audits_df["status"].value_counts()
        for status, count in status_counts.items():
            pct = count / total_count if total_count else 0
            color_map = {"Complete": "#16a34a", "In Progress": "#2563eb", "Fieldwork": "#d97706"}
            color = color_map.get(status, "#6b7280")
            st.markdown(
                f"<div style='display:flex;align-items:center;gap:8px;margin-bottom:6px;'>"
                f"<div style='width:80px;font-size:0.78rem;color:#374151;'>{status}</div>"
                f"<div style='flex:1;background:#f3f4f6;border-radius:4px;height:12px;'>"
                f"<div style='width:{pct*100:.0f}%;background:{color};height:100%;border-radius:4px;'></div>"
                f"</div>"
                f"<div style='width:30px;font-size:0.78rem;color:#6b7280;text-align:right;'>{count}</div>"
                f"</div>",
                unsafe_allow_html=True,
            )

        st.markdown("<div style='height:16px;'></div>", unsafe_allow_html=True)

        # Commentary section
        st.markdown("**Platform Commentary**")
        if commentary:
            st.markdown(
                f"<div style='background:#f8f9fb;border:1px solid #e5e7eb;border-radius:6px;"
                f"padding:14px;font-size:0.85rem;color:#374151;white-space:pre-wrap;'>{commentary}</div>",
                unsafe_allow_html=True,
            )
        else:
            st.markdown(
                "<div style='background:#fef3c7;border:1px solid #f59e0b;border-radius:6px;"
                "padding:14px;font-size:0.82rem;color:#92400e;'>"
                "⚠ No commentary added. Navigate to the Commentary tab to add quarter-end notes."
                "</div>",
                unsafe_allow_html=True,
            )

        st.markdown("<div style='height:8px;'></div>", unsafe_allow_html=True)
        st.markdown(
            "<div style='font-size:0.72rem;color:#9ca3af;text-align:right;'>"
            "Generated by AuditIQ · Draft — not for distribution"
            "</div>",
            unsafe_allow_html=True,
        )
